  CREATE TABLE DES.DBA.Desaparecido (
  id integer IDENTITY,
  nome varchar(200),
  apelido varchar(50),
  data_nascimento varchar(10),
  sexo varchar(10),
  imagem varchar(300),
  idade integer,
  cidade varchar(100),
  estado varchar(100),
  altura float,
  peso float,
  pele varchar(40),
  cor_cabelo varchar(40),
  cor_olhos varchar(40),
  caracteristicas_diversas  varchar(2000),
  data_desaparecimento varchar(10),
  local_desaparecimento varchar(300),
  circunstancia_localizacao varchar(2000),
  data_localizacao varchar(10),
  dados_complementares  varchar(2000),
  situacao varchar(20),
  fonte varchar(400),
  PRIMARY KEY (id)
);